### PR TITLE
Add kube-ps1 support

### PR DESCRIPTION
**Pull request by nacx**
Adds support for: https://github.com/jonmosco/kube-ps1
This is pretty useful when working with Kubernetes and several clusters and namespaces.

It is only supported in `bash` and `zsh` at the moment.

By default, if `kube-ps1` is not installed, it does nothing; if it is enabled, then it prints the Kubernetes context in a line above the prompt. I opted for a multi-line prompt because often the cluster names are long, so that fits better in multiple lines. Also, given that polyglot is using the "pre-prompt" commands, printing the Kubernetes context is done by executing a raw command instead of adding it to the `PS1` variable. This is because having newlines in the prompt and propagating newlines across variables is tricky in `zsh`, so as a pragmatic solution, the Kubrnetes context is printed right before rendering the prompt.

Preview:

tty

### CODE REVIEW

**Comment by agkozak** [comment]
Thanks so much! Give me a few days to play around with this.

**Comment by nacx** [comment]
Sure! I'm a bash user, so probably the zsh limitations I found can be addressed in a more elegant way. Feedback welcome!

**Comment by agkozak** [comment]
I don't use `kubernetes` much myself, but I just installed it and can see why you'd want to have that extra information in your prompt.

I want to make sure, though, that we don't ignore simpler solutions if they exist. For example, it looks as if I can accomplish more or less the same thing in `bash` by loading Polyglot (from the `master` branch) and `kube-ps1` and then typing

    PROMPT_COMMAND+='kube_ps1' 

The newline you want is included in the output.

Likewise, in `zsh` you can load Polyglot (from the `master` branch), source `kube-ps1`, and then type

    PROMPT=$'$(kube_ps1)\n'$PROMPT 

(The `\n` inside the `$'...'` gives you the newline.)

Are those basically functional for you?

**Comment by agkozak** [comment]
Oh, I notice my `zsh` newline doesn't go away when I run `kubeoff`. That would be desirable, wouldn't it?

**Comment by nacx** [comment]
Hmmm It's working for me. Probably due to the zsh version? See screenshot:

screenshot 2019-02-14 at 08 13 41

**Comment by nacx** [comment]
>want to make sure, though, that we don't ignore simpler solutions if they exist

Agree. I did it this way because you need to call `_kube_ps1_update_cache ` (see [here for example](https://github.com/jonmosco/kube-ps1/blob/master/kube-ps1.sh#L60)), otherwise the cluster name and namespace you see won't be refreshed when you change it, and because I changed the default color from red to yellow, which better looks with polyglot default colors.

Also I had the two functions (bash/zsh) because I wanted the kube context in bold (just like the polyglot prompt), and wanted the k8s stuff as encapsulated as possible as it is easy to enable/disable if users don't have the `kube-ps1` tool installed.

**Comment by agkozak** [comment]
> Hmmm It's working for me. Probably due to the zsh version?

Oh, your code works perfectly, and I like the styles. I was just referring to my overly simplistic

    PROMPT=$'$(kube_ps1)\n'$PROMPT

I think the right way to accomplish that would be something like

    _polyglot_kube_ps1_precmd() {
      local kube_ps1=$(kube_ps1)
      [[ -n $kube_ps1 ]] && print -P $kube_ps1 # Conditional newline included
    }
    add-zsh-hook precmd _polyglot_kube_ps1_precmd

Sorry. I'm just thinking out loud.

By the way, doesn't the code you cite show `add-zsh-hook precmd _kube_ps1_update_cache` -- in other words, the cache updating mechanism *is* added to the `precmd` hook in ZSH? It certainly seems to be there when I load `kube-ps1` (you can just type `echo $precmd_functions` to see which functions have been attached to that hook), and it *appears* to work when I change namespace -- but remember, I'm a newbie when it comes to Kubernetes. I could be missing something.

You've done great work. Give me a few days to think about how best to wrap this up.

**Comment by nacx** [comment]
I've made some small improvements taking your suggestions.

>Oh, your code works perfectly, and I like the styles. I was just referring to my overly simplistic

You get that newline because after `kubeoff`, the `$(kube_ps1)` call returns an empty string, so you print an empty string and a newline always.  I struggled a bit with that, trying to make that newline conditional without having to add much crap to the code that builds teh `PS1` variable, and I ended up putting that in its own function as it turned to be the cleaner approach. That also allowed me to add the yellow and bold changes cleanly there, without polluting the existing code.
Probably that could be done differently in bash, but I preferred to have consistency as it would be easier to understand and maintain.

**Comment by agkozak** [comment]
Great work.

You know, I think I'd like to spin your additions off into an add-on package for Polyglot. Polyglot's forte is that it does more or less the same thing in a whole lot of shells; the Kubernetes additions relate only to `bash` and `zsh` and `kube-ps1`. But I was able to recreate your idea as 30 lines of terser, nicer `bash`/`zsh` script (it wouldn't have to be portable beyond that) that could be loaded after Polyglot and `kube-ps1` and accomplish everything we want.

Does that work for you? You'd get full credit for the idea.

The one thing that's bothering me is the Unicode symbol. The Polyglot Prompt itself would never do that -- it's meant to work in all terminals -- but I can understand why many people like that sort of thing. Maybe we could just tolerate it in the add-on.

**Comment by nacx** [comment]
>Does that work for you? You'd get full credit for the idea.

Sure :)

>The one thing that's bothering me is the Unicode symbol. The Polyglot Prompt itself would never do that -- it's meant to work in all terminals -- but I can understand why many people like that sort of thing. Maybe we could just tolerate it in the add-on.

`kube-ps1` already allows to disable that. Users that don't want the symbol or have a terminal where it is not supported can just `export KUBE_PS1_SYMBOL_ENABLE=false`.

**Comment by nacx** [comment]
Regarding the add-on mechanism, I already thought about that, and it would be nice. IMO, though, those are two separate things and that lead me to first implement it as-is, as there are several things to take into account when providing an add-on mechanism (which would be a great addition):

* Which language(s) do we allow for the add-ons?
* Add-ons should be able to customize the prompt... how and where? Before/After/Inside(how?)?
* Need to keep the current simple and "it just works" approach.

I really like the clean and simple approach of this project, and I'd rather see complete features being added. That's why I think the add-on stuff could probably be developed in its own specific PR?

**Comment by agkozak** [comment]
Take a look at this: [agkozak/polyglot-kube-ps1](https://github.com/agkozak/polyglot-kube-ps1/blob/master/polyglot-kube-ps1.sh)

This code should work identically to what you wrote, I think (although I've suppressed the unicode symbol; it can be added back with `KUBE_PS1_SYMBOL_ENABLE=true`). Extra configuration can be done using the settings that `kube-ps1` itself supplies.

What made me decide on add-on status is this: what we're doing is basically creating glue code between my prompt and `kube-ps1`. If I ever include Kubernetes directly into the prompt, it will be as a fully developed feature interacting directly with `kubectl`, not `kube-ps1`. Then I'll be more fully in control of the output and of providing customizations.

>     * Which language(s) do we allow for the add-ons?

I'm not sure what you mean. Human languages or shell languages?

I'm on vacation till Sunday; then I'll take another look at the code and write up a `README.md`.

Thanks again for your great idea. I'll look forward to getting your input on my rewrite.

**Comment by nacx** [comment]
>I'm not sure what you mean. Human languages or shell languages?

Yeah, dismiss that, I misread one of your comments.

Your code looks good except [here](https://github.com/agkozak/polyglot-kube-ps1/blob/master/polyglot-kube-ps1.sh#L34-L36). If I'm not wrong, polyglot resets the PROMPT_COMMAND, so in bash you need to explicitly call `_kube_ps1_update_cache`, as polyglot would remove that from the PROMPT_COMMAND.

Why do you think of that file in another repository? Wouldn't it make sense to have the file in the same repo? Is the approach you envision just to load polyglot, then load any add-on files?

**Comment by agkozak** [comment]
> Your code looks good except [here](https://github.com/agkozak/polyglot-kube-ps1/blob/master/polyglot-kube-ps1.sh#L34-L36). If I'm not wrong, polyglot resets the PROMPT_COMMAND, so in bash you need to explicitly call `_kube_ps1_update_cache`, as polyglot would remove that from the PROMPT_COMMAND.

[Doesn't `kube-ps1` take care of that itself](https://github.com/jonmosco/kube-ps1/blob/master/kube-ps1.sh#L71):

    PROMPT_COMMAND="_kube_ps1_update_cache;${PROMPT_COMMAND:-:}"

I'll take another look at it when I get back.

> Why do you think of that file in another repository? Wouldn't it make sense to have the file in the same repo? Is the approach you envision just to load polyglot, then load any add-on files?

I'm inclined to do that, and then to include documentation in the prompt's `README.md` explaining how to use the two repos together with examples provided.

**Comment by nacx** [comment]
>Doesn't `kube-ps1` take care of that itself

Yes, but if you load polyglot _after_ kube-ps1, it gets [reset](https://github.com/agkozak/polyglot/blob/master/polyglot.sh#L425). 

I've taken your addon example and split all the logic to the addon file and updated the README accordingly. I think it is much cleaner. Also I don't think addons should live in their own repos, as it makes it harder to consume and also harder to keep them up to date with eventual changes to the main file.

**Comment by agkozak** [comment]
My idea is that `kube-ps1`-related code shouldn't make it into the main repo at all. When I'm ready, I'll write all of my own functions to deal with `kubectl`, and they'll work in all the shells.

**Comment by agkozak** [comment]
> Yes, but if you load polyglot _after_ kube-ps1, it gets [reset](https://github.com/agkozak/polyglot/blob/master/polyglot.sh#L425).

Good. Thanks. I'll fix this when I get back.

**Comment by nacx** [comment]
>My idea is that `kube-ps1`-related code shouldn't make it into the main repo at all. When I'm ready, I'll write all of my own functions to deal with `kubectl`, and they'll work in all the shells.

Well, for addons or additions that work, I don't see a reason why they should live in a separate repo, especially taking into account my comment above. I can understand that they don't support all shells polyglot supports, but that's one fo the reasons for having that separated as addons.

Also, writing your own `kubectl` integration is good, but I'm not sure it's worth reinventing the wheel here: most users of kubernetes don't work _only_ with kubernetes, and that means the prompt is usually enabled on demand, via the `kubeon` and `kubeoff` commands, and people using `kube-ps1` is pretty used to it. If you want to provide the same experience, do you pretend to port those comamnds to?

I see the pure `kubectl` path as a potential copying of a bunch of stuff from `kube-ps1` here, and that eventually will get outdated. I'd suggest that effort should be better directed in contributing directly to `kube-ps1` to support other shells nicely, and keep polyglot as a prompt that can integrate nicely with other existing prompts via addons.

**Comment by agkozak** [comment]
All great points. I'll think about it this weekend.

**Comment by nacx** [comment]
Any updates on this?

**Comment by agkozak** [comment]
I've decided to keep the `kube-ps1` integration package in [a separate repo](https://github.com/agkozak/polyglot-kube-ps1/blob/master/polyglot-kube-ps1.sh). It's actually more convenient for ZSH users if we do it that way. We tend to use package managers, so for me it's just

```
zplugin load agkozak/polyglot
zplugin load jonmosco/kube-ps1
zplugin load agkozak/polyglot-kube-ps1
```

Something similar would apply to the other plugin managers. I don't think most people want the extra step of figuring out which exact file to source and where it is and ending up with

```
zplugin load agkozak/polyglot
zplugin load jonmosco/kube-ps1
source $HOME/.zplugin/plugins/agkozak---polyglot/addons/polyglot-kube-ps1.sh
```

I know it's different for `bash` users, who tend not to use plugin managers, but for them it's just the extra step of cloning the extra directory -- nothing more.

Mostly, though, I like things that can be modular to be modular. The `README.md` in `agkozak/polyglot` will explain how to use the `agkozak/polyglot-kube-ps1` add-on.

I think maybe we should keep

    KUBE_PS1_SYMBOL_ENABLE='false'
    KUBE_PS1_CTX_COLOR='yellow'

instead of

    KUBE_PS1_SYMBOL_ENABLE=${KUBE_PS1_SYMBOL_ENABLE:-false}
    KUBE_PS1_CTX_COLOR=${KUBE_PS1_CTX_COLOR:-yellow}

Otherwise those defaults can get defined by `kube-ps1.sh` -- am I wrong? The user can always define alternate settings after sourcing the three files.

You're quite right about putting `_kube_ps1_update_cache` into `_polyglot_kube_ps1_prompt_command`. I've just added  [a line](https://github.com/agkozak/polyglot-kube-ps1/blob/master/polyglot-kube-ps1.sh#L31) to make sure that it doesn't run twice.

`kube-ps1` doesn't check to see whether a user's terminal supports color, so for now, we don't need to either -- anyone who uses our add-on will know what he or she is getting into. Someone could add support for monochrome terminals to `kube-ps1` as a nice little project.

`kube-ps1` doesn't output `\[` `\]` escape sequence delimiters in `bash`. That's another great improvement that could easily be added to `kube-ps1`. I don't think we'll address it here.

**Comment by nacx** [comment]
Looks good to me.
You could add an image like the one in [my dotfiles repo](https://github.com/nacx/dotfiles) or int his PR for how the prompt looks like with the `kube-ps1` addon enabled.
I'm closing the PR. Thanks!

**Comment by agkozak** [comment]
Thanks so much for your contribution. I've got a new point release going out soon - I'll get the documentation under control.

**Pull request closed without merging**
